"use client";
import{useEffect,useState}from"react";
type F={id:string;name:string;size:number;mime_type:string};type R={id:string;item:string;owner:string;progress:string;status:string;start_date:string|null;due_date:string|null;files:F[]};type S={id:string;name:string;rows:R[]};type P={id:string;name:string;pages:{id:string;title:string;name?:string;sections:S[]}[]};
const st=["持續進行中","月初及月底","已完成","暫時結案","待確認"];const sz=(n:number)=>n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
export default function Home(){const[ps,setPs]=useState<any[]>([]),[pid,setPid]=useState(""),[d,setD]=useState<P|null>(null),[pg,setPg]=useState(""),[q,setQ]=useState(""),[toast,setToast]=useState("");
const loadP=async()=>{const x=await fetch("/api/projects").then(r=>r.json());setPs(x);if(!pid&&x[0])setPid(x[0].id)};const load=async(id:string)=>{setD(await fetch("/api/projects/"+id).then(r=>r.json()))};useEffect(()=>{loadP()},[]);useEffect(()=>{if(pid)load(pid)},[pid]);useEffect(()=>{if(d&&!pg)setPg(d.pages?.[0]?.id||"")},[d,pg]);
const page=d?.pages.find(x=>x.id===pg);const mut=async(b:any)=>{const r=await fetch(`/api/projects/${pid}/data`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});if(!r.ok)throw Error((await r.json()).error);return r.json()};const reload=()=>load(pid);
const newP=async()=>{const n=prompt("專案名稱");if(!n)return;const r=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:n})});const x=await r.json();await loadP();setPid(x.id)};const addPage=async()=>{await mut({action:"createPage",title:"新頁面"});await reload()};const addSec=async()=>{if(page){await mut({action:"createSection",pageId:page.id,name:"新分類"});await reload()}};const addRow=async(s:S)=>{await mut({action:"createRow",sectionId:s.id});await reload()};
const update=async(action:string,b:any)=>{try{await mut({action,...b});await reload()}catch(e:any){alert(e.message)}};const upload=async(s:S,r:R,l:FileList|null)=>{if(!l)return;for(const f of Array.from(l)){const form=new FormData();form.append("rowId",r.id);form.append("file",f);const x=await fetch(`/api/projects/${pid}/files`,{method:"POST",body:form});if(!x.ok){alert((await x.json()).error);break}}await reload();setToast("檔案已上傳");setTimeout(()=>setToast(""),2000)};const share=async()=>{const x=await mut({action:"share"});try{await navigator.clipboard.writeText(x.url)}catch{}setToast("分享網址已複製");setTimeout(()=>setToast(""),2500)};
if(!d)return <div className="loading">雲端資料載入中…</div>;
return <main className="app"><aside className="side"><h2>◆ Notion Lite Cloud</h2><button className="dark" onClick={newP}>＋ 新增專案</button><p>工作區</p>{ps.map(x=><button className={"nav "+(x.id===pid?"sel":"")} onClick={()=>{setPid(x.id);setPg("")}}>📋 {x.name}</button>)}</aside><section className="main"><header><b>📋 {d.name}</b><div><input placeholder="搜尋…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={share}>🔗 建立分享網址</button></div></header><div className="layout"><nav className="pages"><b>頁面</b><button onClick={addPage}>＋ 新增頁面</button>{d.pages.map(x=><button className={x.id===pg?"sel":""} onClick={()=>setPg(x.id)}>📄 {x.title || x.name}</button>)}</nav><article><div className="head"><div><input className="title" value={page?.title || page?.name || ""} onChange={e=>page&&update("updatePage",{id:page.id,name:e.target.value})}/><p>☁️ 雲端同步：不同電腦看到同一份資料與檔案。</p></div><button onClick={addSec}>＋ 新分類</button></div>{page?.sections.map(s=><section className="card"><div className="sect"><input value={s.name} onChange={e=>update("updateSection",{id:s.id,name:e.target.value})}/><button onClick={()=>addRow(s)}>＋ 新增專案</button></div><div className="scroll"><table><thead><tr><th>Item</th><th>擔當者</th><th>目前執行狀況</th><th>狀態</th><th>開案日期</th><th>限期日期</th><th>檔案</th></tr></thead><tbody>{s.rows.filter(r=>(s.name+" "+Object.values(r).join(" ")).toLowerCase().includes(q.toLowerCase())).map(r=><tr><td><input value={r.item||""} onChange={e=>update("updateRow",{id:r.id,item:e.target.value})}/></td><td><input value={r.owner||""} onChange={e=>update("updateRow",{id:r.id,owner:e.target.value})}/></td><td><textarea value={r.progress||""} onChange={e=>update("updateRow",{id:r.id,progress:e.target.value})}/></td><td><select value={r.status||"待確認"} onChange={e=>update("updateRow",{id:r.id,status:e.target.value})}>{st.map(x=><option>{x}</option>)}</select></td><td><input type="date" value={r.start_date||""} onChange={e=>update("updateRow",{id:r.id,start_date:e.target.value})}/></td><td><input type="date" value={r.due_date||""} onChange={e=>update("updateRow",{id:r.id,due_date:e.target.value})}/></td><td><div className="files">{r.files?.map(f=><div className="file"><span>{f.mime_type?.startsWith("image/")?"🖼️":f.mime_type==="application/pdf"?"📕":"📄"}</span><strong title={f.name}>{f.name}<small> {sz(f.size)}</small></strong><a href={`/api/files/${f.id}?mode=open`} target="_blank">開啟</a><a href={`/api/files/${f.id}?mode=download`}>下載</a><button onClick={async()=>{if(!confirm("刪除檔案？"))return;await fetch(`/api/projects/${pid}/files/delete`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileId:f.id})});await reload()}}>刪除</button></div>)}<label className="upload">＋ 上傳檔案<input type="file" multiple onChange={e=>{upload(s,r,e.target.files);e.currentTarget.value=""}}/></label></div></td></tr>)}</tbody></table></div></section>)}</article></div></section>{toast&&<div className="toast">{toast}</div>}</main>}
